server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: potato
    password: 123456
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      #ddl-auto: create #create update none
       ddl-auto: update
       naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    